### ISSUE TITLE
shop-wrapper.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [IrrationalPattern/angular5-training#2]
я хотел, чтобы вы попробовали использовать альтернативный блок, если корзина пустая.
<app-cart
      *ngIf="isShowCart"
      [products]="cartProducts"
      (cartProductRemoved)="onCartProductRemoved($event)">
    </app-cart>

**Comment by IrrationalPattern** [comment]
Понял, упустил этот момент.
Сделаю таким образом в task2.
